"use client";
import { useEffect, useMemo, useRef, useState } from "react";

type MissionId="palace"|"castle"|"ranch"|"mansion"|"apartment"|"cottage"|"cafe"|"money";
type Student={id:string;grade:string;classNo:string;number:string;name:string;studyTasks?:string[];lifeTasks?:string[];studyTask?:string;lifeTask?:string;extra1:string;extra2:string;mission:MissionId;startDate:string;checks:Record<string,string[]>};
const MISSIONS:{id:MissionId;label:string;icon:string;color:string;desc:string}[]=[
 {id:"palace",label:"왕궁",icon:"🏰",color:"#3155a6",desc:"푸른 지붕과 꽃 정원이 자라요"},{id:"castle",label:"성",icon:"🏯",color:"#765f50",desc:"튼튼한 성벽과 탑을 완성해요"},{id:"ranch",label:"목장",icon:"🐴",color:"#4f8a55",desc:"들판에 동물 친구들이 모여요"},{id:"mansion",label:"대저택",icon:"🏛️",color:"#a26678",desc:"정원과 멋진 방을 꾸며요"},{id:"apartment",label:"아파트",icon:"🏢",color:"#4e789a",desc:"나만의 생활공간을 만들어요"},{id:"cottage",label:"전원주택",icon:"🏡",color:"#6d8b42",desc:"텃밭과 꽃길이 생겨나요"},{id:"cafe",label:"카페",icon:"☕",color:"#a45f3e",desc:"따뜻한 나만의 카페를 열어요"},{id:"money",label:"돈 모으기",icon:"🐷",color:"#db6f8b",desc:"돼지저금통과 꿈 통장이 자라요"}];
const STUDY=["매일 수업 시작 5분 전에 다음 수업을 준비하기","매일 수업 전 5분 동안 나의 학습계획 실천하기","매일 수학 문제 5개 풀기","매일 영어 단어 20개 이상 익히기","매일 책을 20분 이상 읽기","그날 배운 내용을 10분 동안 복습하기","학교에서 받은 과제를 정해진 날까지 완료하기","수업 시간에 한 번 이상 질문하거나 발표하기"];
const LIFE=["매일 30분 정도 운동하기","잠자기 전에 다음 날 가방 정리하기","사용한 물건을 제자리에 정리하기","친구에게 따뜻한 말 한 번 건네기","가족에게 먼저 인사하기","정해진 시간에 잠자리에 들기","비속어를 사용하지 않고 바른말 쓰기"];
const KEY="promise-challenge-v1",today=()=>new Date().toISOString().slice(0,10);
const fmt=(d:string)=>new Date(d+"T12:00:00").toLocaleDateString("ko-KR",{month:"long",day:"numeric",weekday:"short"});
const taskList=(s:Student,type:"study"|"life")=>type==="study"?(s.studyTasks?.length?s.studyTasks:[s.studyTask||""]):(s.lifeTasks?.length?s.lifeTasks:[s.lifeTask||""]);
const hasCheck=(keys:string[],type:"study"|"life",i:number,total:number)=>keys.includes(`${type}${i}`)||(total===1&&keys.includes(type));
const categoryDone=(s:Student,keys:string[],type:"study"|"life")=>taskList(s,type).every((_,i,a)=>hasCheck(keys,type,i,a.length));
const days=(s:Student)=>Object.values(s.checks).filter(v=>categoryDone(s,v,"study")&&categoryDone(s,v,"life")).length;
const growth=(s:Student)=>Object.values(s.checks).reduce((sum,v)=>sum+(categoryDone(s,v,"study")&&categoryDone(s,v,"life")?1:0)+(v.includes("extra1")?.5:0)+(v.includes("extra2")?.5:0),0);
function streak(s:Student){let n=0,d=new Date();for(let i=0;i<100;i++){const v=s.checks[d.toISOString().slice(0,10)]||[];if(categoryDone(s,v,"study")&&categoryDone(s,v,"life"))n++;else if(i>0)break;d.setDate(d.getDate()-1)}return n}

export default function Home(){
 const [students,setStudents]=useState<Student[]>([]),[activeId,setActiveId]=useState<string|null>(null),[tab,setTab]=useState("today"),[setup,setSetup]=useState(false),[step,setStep]=useState(0),[reward,setReward]=useState(false),[adminMode,setAdminMode]=useState(false),[zoom,setZoom]=useState(false);
 const [form,setForm]=useState({grade:"1",classNo:"1",number:"1",name:"",studyTasks:[] as string[],lifeTasks:[] as string[],studyCustom:"",lifeCustom:"",extra1:"",extra2:"",mission:"palace" as MissionId});const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const r=localStorage.getItem(KEY);if(r)setStudents(JSON.parse(r))}catch{}},[]);useEffect(()=>{if(students.length)localStorage.setItem(KEY,JSON.stringify(students))},[students]);
 const active=students.find(s=>s.id===activeId)||null,cur=active?.checks[today()]||[],total=active?days(active):0,mission=MISSIONS.find(m=>m.id===active?.mission)||MISSIONS[0];
 function create(){const study=[...form.studyTasks,form.studyCustom.trim()].filter(Boolean).slice(0,3),life=[...form.lifeTasks,form.lifeCustom.trim()].filter(Boolean).slice(0,3);if(!form.name.trim()||!study.length||!life.length)return;const s:Student={grade:form.grade,classNo:form.classNo,number:form.number,name:form.name.trim(),studyTasks:study,lifeTasks:life,extra1:form.extra1,extra2:form.extra2,mission:form.mission,id:`${form.grade}-${form.classNo}-${form.number}-${Date.now()}`,startDate:today(),checks:{}};setStudents(v=>[...v,s]);setActiveId(s.id);setSetup(false);setStep(0);setTab("today")}
 function toggle(k:string){if(!active)return;const before=categoryDone(active,cur,"study")&&categoryDone(active,cur,"life"),next=cur.includes(k)?cur.filter(x=>x!==k):[...cur,k],after=categoryDone(active,next,"study")&&categoryDone(active,next,"life");setStudents(v=>v.map(s=>s.id===active.id?{...s,checks:{...s.checks,[today()]:next}}:s));if(!before&&after&&(total+1)%5===0)setTimeout(()=>setReward(true),250)}
 function backup(){const b=new Blob([JSON.stringify({app:"나의 약속 챌린지",version:1,exportedAt:new Date().toISOString(),students},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=`나의약속챌린지_백업_${today()}.json`;a.click();URL.revokeObjectURL(a.href)}
 function removeStudent(id:string){const target=students.find(s=>s.id===id);if(!target||!confirm(`${target.grade}학년 ${target.classNo}반 ${target.number}번 ${target.name} 학생의 자료를 삭제할까요?`))return;backup();const next=students.filter(s=>s.id!==id);setStudents(next);if(!next.length)localStorage.removeItem(KEY)}
 function removeAll(){if(!students.length)return;if(!confirm(`전체 ${students.length}명의 자료를 삭제할까요? 삭제 전에 백업파일이 내려받아집니다.`))return;backup();setStudents([]);localStorage.removeItem(KEY)}
 function restore(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(String(r.result));if(!Array.isArray(d.students))throw 0;if(confirm(`${d.students.length}명의 기록을 가져올까요?`)){setStudents(d.students);setActiveId(null);alert("자료를 정상적으로 가져왔습니다.")}}catch{alert("올바른 백업파일이 아닙니다.")}};r.readAsText(f);e.target.value=""}
 if(setup)return <Setup form={form} setForm={setForm} step={step} setStep={setStep} done={create} cancel={()=>{setSetup(false);setStep(0)}}/>;
 if(adminMode)return <AdminScreen students={students} close={()=>setAdminMode(false)} backup={backup} restore={restore} removeStudent={removeStudent} removeAll={removeAll} fileRef={fileRef}/>;
 if(!active)return <main className="landing"><button className="admin-entry" onClick={()=>setAdminMode(true)}>⚙ 관리자</button><div className="orb a"/><div className="orb b"/><section className="welcome"><div className="brand">✓</div><p className="eyebrow">12주 동안 나와 지키는 약속</p><h1>나의 약속 챌린지</h1><p className="lead">매일 작은 실천을 기록하고<br/>나만의 멋진 미션을 완성해요.</p>{students.length>0&&<div className="student-list"><p>내 기록 찾기</p>{students.map(s=><button key={s.id} onClick={()=>setActiveId(s.id)}><span>{MISSIONS.find(m=>m.id===s.mission)?.icon}</span><span><b>{s.grade}학년 {s.classNo}반 {s.number}번 {s.name}</b><small>{MISSIONS.find(m=>m.id===s.mission)?.label} · {days(s)}일 달성</small></span><i>›</i></button>)}</div>}<button className="primary jumbo" onClick={()=>setSetup(true)}>＋ 새 도전 시작하기</button><small className="privacy">이 기록은 현재 기기에만 저장됩니다 · 학교 공용 컴퓨터를 공식 기록기기로 사용하세요</small></section></main>;
 return <main className="shell"><header><button className="logo" onClick={()=>setActiveId(null)}><span>✓</span> 나의 약속 챌린지</button><div className="student-chip"><b>{active.grade}학년 {active.classNo}반 {active.number}번</b><span>{active.name}</span><button onClick={()=>setActiveId(null)}>나가기</button></div></header><nav>{[["today","✓","오늘의 실천"],["challenge","◷","나의 도전"],["mission","★","나의 미션"],["history","▥","성장기록"],["intro","▦","미션 그림 소개"]].map(([k,i,l])=><button key={k} className={tab===k?"on":""} onClick={()=>setTab(k)}><i>{i}</i>{l}</button>)}</nav><section className="content">
 {tab==="today"&&<><Heading over={fmt(today())} title="오늘도 약속을 실천해 볼까요?" side={<div className="streak">🔥 <b>{streak(active)}일</b><span>연속 실천</span></div>}/><div className="today-grid"><div className="tasks">{taskList(active,"study").map((text,i,a)=><Task key={`study${i}`} kind="study" title={`학습 실천과제 ${a.length>1?i+1:""}`} text={text} checked={hasCheck(cur,"study",i,a.length)} required onClick={()=>toggle(`study${i}`)}/>)}{taskList(active,"life").map((text,i,a)=><Task key={`life${i}`} kind="life" title={`생활 실천과제 ${a.length>1?i+1:""}`} text={text} checked={hasCheck(cur,"life",i,a.length)} required onClick={()=>toggle(`life${i}`)}/>)}{(active.extra1||active.extra2)&&<div className="bonus-guide">🚀 기타 실천과제는 보너스로 기록돼요. 그림은 필수 약속을 모두 지킨 날마다 60분의 1씩 색칠됩니다.</div>}{active.extra1&&<Task kind="extra" title="기타 실천과제 1 · 보너스 +0.5" text={active.extra1} checked={cur.includes("extra1")} onClick={()=>toggle("extra1")}/>} {active.extra2&&<Task kind="extra" title="기타 실천과제 2 · 보너스 +0.5" text={active.extra2} checked={cur.includes("extra2")} onClick={()=>toggle("extra2")}/>} {categoryDone(active,cur,"study")&&categoryDone(active,cur,"life")&&<div className="complete">✨ 오늘의 필수 약속을 모두 지켰어요!<strong>밑그림에 오늘의 색깔이 새롭게 채워졌어요.</strong></div>}</div><Preview s={active} total={total} onOpen={()=>setZoom(true)}/></div></>}
 {tab==="challenge"&&<><Heading over="나의 12주 도전" title={`${active.name} 학생의 꾸준한 발걸음`}/><div className="stats"><Stat n={`${total}일`} l="필수과제 달성"/><Stat n={`${streak(active)}일`} l="연속 실천"/><Stat n={`${Math.min(100,Math.round(total/60*100))}%`} l="미션 완성도"/><Stat n={`${growth(active)-total}점`} l="기타과제 보너스"/></div><div className="challenge"><div className="ring" style={{"--p":`${Math.min(100,total/60*100)*3.6}deg`} as React.CSSProperties}><b>{Math.min(100,Math.round(total/60*100))}%</b><span>완성</span></div><div><p className="eyebrow">선택한 미션</p><h3>{active.name}의 {mission.label}</h3><p>필수 약속을 지킨 하루마다 밑그림에 60분의 1씩 색깔이 채워집니다.</p><div className="progress"><i style={{width:`${Math.min(100,total/60*100)}%`}}/></div><small>60일 목표 중 {total}일의 색칠을 완성했어요</small></div></div></>}
 {tab==="mission"&&<><Heading over="나의 미션" title={`${active.name}의 ${mission.label}`}/><Stage s={active} total={total} onOpen={()=>setZoom(true)}/></>}
 {tab==="history"&&<History s={active}/>} {tab==="intro"&&<MissionIntro/>}
 </section>{reward&&<div className="modal"><div className="reward"><div>🎉</div><h2>5일 실천에 성공했어요!</h2><p>꾸준히 약속을 지킨 여러분이 자랑스러워요.</p><strong>상품을 선생님께 받아 가세요!</strong><button className="primary" onClick={()=>setReward(false)}>확인했어요</button></div></div>}{zoom&&<div className="image-modal" onClick={()=>setZoom(false)}><button aria-label="전체화면 닫기">×</button><div className="full-art growing-art" style={{"--reveal":`${progressPercent(total)}%`} as React.CSSProperties} onClick={e=>e.stopPropagation()}><MissionArt mission={active.mission}/><div className="plaque">{active.name}의 {mission.label}</div><div className="full-progress">실천 {total}일 · {Math.round(progressPercent(total))}% 채색</div></div></div>}</main>
}

function AdminScreen({students,close,backup,restore,removeStudent,removeAll,fileRef}:{students:Student[];close:()=>void;backup:()=>void;restore:(e:React.ChangeEvent<HTMLInputElement>)=>void;removeStudent:(id:string)=>void;removeAll:()=>void;fileRef:React.RefObject<HTMLInputElement|null>}){
 const [unlocked,setUnlocked]=useState(false),[pin,setPin]=useState(""),[error,setError]=useState(false);
 function enter(){if(pin==="6673"){setUnlocked(true);setError(false)}else{setError(true);setPin("")}}
 if(!unlocked)return <main className="admin-page"><section className="admin-login"><button className="back" onClick={close}>← 첫 화면</button><div className="admin-lock">🔒</div><p className="eyebrow">교사 전용</p><h1>관리자 화면</h1><p>관리 비밀번호 4자리를 입력하세요.</p><input type="password" inputMode="numeric" maxLength={4} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))} onKeyDown={e=>{if(e.key==="Enter")enter()}} autoFocus aria-label="관리자 비밀번호"/>{error&&<small className="pin-error">비밀번호가 맞지 않습니다.</small>}<button className="primary" disabled={pin.length!==4} onClick={enter}>관리자 화면 열기</button></section></main>;
 return <main className="admin-page"><section className="admin-panel"><div className="admin-head"><div><p className="eyebrow">교사 전용 관리</p><h1>학생 기록 관리</h1><span>등록 학생 {students.length}명</span></div><button onClick={close}>× 닫기</button></div><div className="admin-grid"><button onClick={backup}><span>↓</span><b>전체 자료 백업하기</b><small>{students.length}명의 기록을 파일로 저장합니다.</small></button><button onClick={()=>fileRef.current?.click()}><span>↑</span><b>백업자료 가져오기</b><small>저장해 둔 기록을 이 컴퓨터에 복원합니다.</small></button><input ref={fileRef} type="file" accept=".json" hidden onChange={restore}/></div><div className="warning">삭제하면 먼저 전체 백업파일이 자동으로 내려받아집니다.</div><div className="manage-list"><h2>학생별 자료 삭제</h2>{students.length?students.map(s=><div key={s.id}><span className="student-avatar">{MISSIONS.find(m=>m.id===s.mission)?.icon}</span><span><b>{s.grade}학년 {s.classNo}반 {s.number}번 {s.name}</b><small>{MISSIONS.find(m=>m.id===s.mission)?.label} · {days(s)}일 달성 · 성장 {growth(s)}점</small></span><button onClick={()=>removeStudent(s.id)}>삭제</button></div>):<p className="empty">등록된 학생 자료가 없습니다.</p>}</div>{students.length>0&&<button className="delete-all" onClick={removeAll}>전체 학생 자료 삭제</button>}</section></main>
}

function Setup({form,setForm,step,setStep,done,cancel}:{form:any;setForm:any;step:number;setStep:any;done:()=>void;cancel:()=>void}){const studyCount=form.studyTasks.length+(form.studyCustom.trim()?1:0),lifeCount=form.lifeTasks.length+(form.lifeCustom.trim()?1:0),ok=step===0?form.name.trim():step===1?studyCount>0:step===2?lifeCount>0:true;return <main className="setup"><section className="setup-card"><button className="back" onClick={step?()=>setStep(step-1):cancel}>← 이전</button><div className="steps">{[0,1,2,3,4].map(i=><i key={i} className={i<=step?"on":""}/>)}</div>{step===0&&<><p className="eyebrow">1 / 5 · 학생정보</p><h1>나의 도전을 시작해요</h1><p className="sub">기록을 찾을 때 사용할 정보를 입력하세요.</p><div className="fields">{[["학년","grade",3],["반","classNo",6]].map(([l,k,n]:any)=><label key={k}>{l}<select value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}>{Array.from({length:n},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label>)}<label>번호<input type="number" min="1" max="40" value={form.number} onChange={e=>setForm({...form,number:e.target.value})}/></label><label>이름<input placeholder="이름" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label></div></>}{step===1&&<TaskSetup n="2" type="학습" title="학습 실천과제를 정해요" guide="예시를 체크하고 직접 입력도 함께 할 수 있어요. 최대 3개를 선택하세요." examples={STUDY} selected={form.studyTasks} custom={form.studyCustom} changeSelected={(v:string[])=>setForm({...form,studyTasks:v})} changeCustom={(v:string)=>setForm({...form,studyCustom:v})}/>} {step===2&&<TaskSetup n="3" type="생활" title="생활 실천과제를 정해요" guide="예시를 체크하고 직접 입력도 함께 할 수 있어요. 최대 3개를 선택하세요." examples={LIFE} selected={form.lifeTasks} custom={form.lifeCustom} changeSelected={(v:string[])=>setForm({...form,lifeTasks:v})} changeCustom={(v:string)=>setForm({...form,lifeCustom:v})}/>} {step===3&&<><p className="eyebrow">4 / 5 · 선택사항</p><h1>더 도전해 볼까요?</h1><p className="sub">기타과제는 하나를 완료할 때마다 미션 성장점수 0.5점을 더 받아요.</p><label className="wide">기타 실천과제 1<input placeholder="예: 가족에게 먼저 인사하기" value={form.extra1} onChange={e=>setForm({...form,extra1:e.target.value})}/></label><label className="wide">기타 실천과제 2<input placeholder="예: 사용한 물건 제자리에 놓기" value={form.extra2} onChange={e=>setForm({...form,extra2:e.target.value})}/></label></>} {step===4&&<><p className="eyebrow">5 / 5 · 미션 선택</p><h1>3개월 동안 무엇을 완성할까요?</h1><p className="sub">마음에 드는 미션 하나를 선택하세요.</p><div className="mission-select">{MISSIONS.map(m=><button key={m.id} onClick={()=>setForm({...form,mission:m.id})} className={form.mission===m.id?"chosen":""} style={{"--mission":m.color} as React.CSSProperties}><span>{m.icon}</span><b>{m.label}</b><small>{m.desc}</small><i>✓</i></button>)}</div></>}<div className="setup-actions"><button className="primary" disabled={!ok} onClick={step<4?()=>setStep(step+1):done}>{step<4?"다음":"이 약속으로 도전 시작하기"}</button></div></section></main>}
function TaskSetup({n,type,title,guide,examples,selected,custom,changeSelected,changeCustom}:{n:string;type:string;title:string;guide:string;examples:string[];selected:string[];custom:string;changeSelected:(v:string[])=>void;changeCustom:(v:string)=>void}){const count=selected.length+(custom.trim()?1:0);function pick(x:string){if(selected.includes(x))changeSelected(selected.filter(v=>v!==x));else if(count<3)changeSelected([...selected,x])}return <><p className="eyebrow">{n} / 5 · {type} 실천과제 <em>1~3개</em></p><h1>{title}</h1><p className="sub">{guide} <b className="count">현재 {count}/3개</b></p><div className="examples">{examples.map(x=><button key={x} className={selected.includes(x)?"selected":""} disabled={!selected.includes(x)&&count>=3} onClick={()=>pick(x)}><i>{selected.includes(x)?"✓":"○"}</i>{x}</button>)}</div><label className="wide">직접 입력하기<textarea placeholder="선택한 예시와 함께 나만의 과제도 추가할 수 있어요." value={custom} disabled={!custom&&selected.length>=3} onChange={e=>changeCustom(e.target.value)}/></label></>}
function Heading({over,title,side}:{over:string;title:string;side?:React.ReactNode}){return <div className="heading"><div><p>{over}</p><h2>{title}</h2></div>{side}</div>}
function Task({kind,title,text,checked,required,onClick}:{kind:string;title:string;text:string;checked:boolean;required?:boolean;onClick:()=>void}){return <button className={`task ${kind} ${checked?"done":""}`} onClick={onClick}><span>{kind==="study"?"📘":kind==="life"?"🌿":"⭐"}</span><span><small>{title} {required&&<em>필수</em>}</small><b>{text}</b></span><i>{checked?"✓":""}</i></button>}
const progressPercent=(total:number)=>Math.min(100,total/60*100);
function MissionArt({mission}:{mission:MissionId}){const image=`url('/missions/${mission}.webp')`;return <><span className="mission-sketch" style={{backgroundImage:image}} aria-hidden="true"/><span className="mission-reveal" style={{backgroundImage:image}} aria-hidden="true"/></>}
function Preview({s,total,onOpen}:{s:Student;total:number;onOpen:()=>void}){const m=MISSIONS.find(x=>x.id===s.mission)!;const percent=progressPercent(total);return <button aria-label={`${m.label} 그림 전체화면으로 보기`} className="preview growing-art" style={{"--reveal":`${percent}%`} as React.CSSProperties} onClick={onOpen}><MissionArt mission={s.mission}/><div><p>{s.name}의</p><h3>{m.label}</h3><div className="progress light"><i style={{width:`${percent}%`}}/></div><small>{Math.round(percent)}% 채색 · 실천 {total}일</small><em>⛶ 그림을 누르면 크게 볼 수 있어요</em></div></button>}
function Stage({s,total,onOpen}:{s:Student;total:number;onOpen:()=>void}){const m=MISSIONS.find(x=>x.id===s.mission)!;const level=Math.min(7,Math.floor(total/10)+1),percent=progressPercent(total);return <button aria-label={`${m.label} 그림 전체화면으로 보기`} className="stage growing-art" style={{"--reveal":`${percent}%`} as React.CSSProperties} onClick={onOpen}><MissionArt mission={s.mission}/><div className="plaque">{s.name}의 {m.label}</div><div className="stage-info"><span>채색단계 {level} / 7</span><b>{total<60?`${60-total}일 더 실천하면 최종 완성!`:"60일 미션을 완성했어요!"}</b><p>{total===0?"연필 밑그림에서 시작해요.":total<30?"하루하루 색깔이 채워지고 있어요.":total<60?"완성 그림에 점점 가까워지고 있어요.":"나만의 미션이 완성됐어요!"} · 눌러서 크게 보기</p></div></button>}
function MissionIntro(){const [selected,setSelected]=useState<MissionId>("palace"),mission=MISSIONS.find(m=>m.id===selected)!;const milestones=[0,10,20,30,40,50,60];return <><Heading over="누구나 볼 수 있는 안내" title="미션 그림이 완성되는 과정"/><p className="intro-lead">그림을 선택하면 완성 모습과 60일 동안 밑그림에 색이 채워지는 과정을 볼 수 있어요.</p><div className="intro-missions">{MISSIONS.map(m=><button key={m.id} className={selected===m.id?"selected":""} onClick={()=>setSelected(m.id)}><span>{m.icon}</span><b>{m.label}</b></button>)}</div><section className="intro-showcase"><div className="intro-final" style={{backgroundImage:`url('/missions/${mission.id}.webp')`}}><strong>{mission.label} 최종 완성 모습</strong></div><div><p className="eyebrow">60일 채색 과정</p><h3>밑그림에서 완성 그림까지</h3><p>필수 약속을 모두 지킨 날마다 그림에 60분의 1씩 색깔이 채워집니다.</p></div></section><div className="milestone-grid">{milestones.map(day=><div key={day}><div className="milestone-art growing-art" style={{"--reveal":`${progressPercent(day)}%`} as React.CSSProperties}><MissionArt mission={selected}/></div><b>{day===0?"시작 전":`${day}일`}</b><span>{day===0?"연필 밑그림":day===60?"전체 완성":`${Math.round(progressPercent(day))}% 채색`}</span></div>)}</div></>}
function Stat({n,l}:{n:string;l:string}){return <div className="stat"><b>{n}</b><span>{l}</span></div>}
function History({s}:{s:Student}){const es=useMemo(()=>Object.entries(s.checks).sort((a,b)=>b[0].localeCompare(a[0])),[s.checks]);return <><Heading over="자동 성장기록" title="실천한 날이 차곡차곡 기록돼요"/><div className="history-summary"><b>총 {days(s)}일 달성 · 성장 {growth(s)}점</b><span>필수과제 달성일과 기타과제 보너스를 자동으로 계산합니다.</span></div><div className="history-list">{es.length?es.map(([d,k])=>{const sd=categoryDone(s,k,"study"),ld=categoryDone(s,k,"life"),bonus=(k.includes("extra1")?.5:0)+(k.includes("extra2")?.5:0);return <div key={d}><time>{fmt(d)}</time><span className={sd?"ok":""}>학습 {sd?"✓":"—"}</span><span className={ld?"ok":""}>생활 {ld?"✓":"—"}</span><b>{sd&&ld?`달성${bonus?` +${bonus}`:""}`:"진행 중"}</b></div>}):<div className="empty">아직 기록이 없습니다. 오늘의 첫 약속을 실천해 보세요!</div>}</div></>}
