"use client";
import { useEffect, useMemo, useRef, useState } from "react";

type MissionId="palace"|"castle"|"ranch"|"mansion"|"apartment"|"cottage"|"cafe"|"money";
type ColorMode="auto"|"manual";
type Student={id:string;grade:string;classNo:string;number:string;name:string;studyTasks?:string[];lifeTasks?:string[];studyTask?:string;lifeTask?:string;extra1:string;extra2:string;mission:MissionId;startDate:string;checks:Record<string,string[]>;colorMode?:ColorMode;colorAllocations?:number[];selectedColorPart?:number;unspentColorDays?:number};
const MISSIONS:{id:MissionId;label:string;icon:string;color:string;desc:string}[]=[
 {id:"palace",label:"왕궁",icon:"🏰",color:"#3155a6",desc:"푸른 지붕과 꽃 정원이 자라요"},{id:"castle",label:"성",icon:"🏯",color:"#765f50",desc:"튼튼한 성벽과 탑을 완성해요"},{id:"ranch",label:"목장",icon:"🐴",color:"#4f8a55",desc:"들판에 동물 친구들이 모여요"},{id:"mansion",label:"대저택",icon:"🏛️",color:"#a26678",desc:"정원과 멋진 방을 꾸며요"},{id:"apartment",label:"아파트",icon:"🏢",color:"#4e789a",desc:"나만의 생활공간을 만들어요"},{id:"cottage",label:"전원주택",icon:"🏡",color:"#6d8b42",desc:"텃밭과 꽃길이 생겨나요"},{id:"cafe",label:"카페",icon:"☕",color:"#a45f3e",desc:"따뜻한 나만의 카페를 열어요"},{id:"money",label:"돈 모으기",icon:"🐷",color:"#db6f8b",desc:"돼지저금통과 꿈 통장이 자라요"}];
type ColorPart={name:string;clip:string};
const COLOR_PARTS:Record<MissionId,ColorPart[]>={
 palace:[
  {name:"왕궁 정문",clip:"polygon(39% 48%,61% 48%,63% 72%,37% 72%)"},{name:"왕궁 본관",clip:"polygon(29% 25%,71% 25%,73% 61%,27% 61%)"},{name:"왼쪽 탑",clip:"polygon(7% 22%,35% 22%,37% 63%,5% 67%)"},{name:"오른쪽 탑",clip:"polygon(65% 22%,93% 22%,95% 67%,63% 63%)"},
  {name:"푸른 지붕과 첨탑",clip:"polygon(8% 0%,92% 0%,91% 37%,68% 31%,50% 39%,32% 31%,9% 37%)"},{name:"정원 분수",clip:"polygon(27% 58%,73% 58%,77% 88%,23% 88%)"},{name:"왼쪽 꽃밭",clip:"polygon(0% 57%,39% 54%,43% 100%,0% 100%)"},{name:"오른쪽 꽃밭",clip:"polygon(61% 54%,100% 57%,100% 100%,57% 100%)"},
  {name:"왼쪽 나무",clip:"polygon(0% 12%,22% 9%,27% 69%,0% 74%)"},{name:"오른쪽 나무",clip:"polygon(78% 9%,100% 12%,100% 74%,73% 69%)"},{name:"하늘과 구름",clip:"polygon(0% 0%,100% 0%,100% 25%,0% 25%)"},{name:"왕궁 산책로",clip:"polygon(22% 82%,78% 82%,100% 100%,0% 100%)"}],
 castle:[
  {name:"성문",clip:"polygon(40% 50%,60% 50%,62% 78%,38% 78%)"},{name:"중앙 본성",clip:"polygon(27% 22%,73% 22%,75% 62%,25% 62%)"},{name:"왼쪽 성탑",clip:"polygon(5% 25%,34% 25%,36% 70%,3% 73%)"},{name:"오른쪽 성탑",clip:"polygon(66% 25%,95% 25%,97% 73%,64% 70%)"},
  {name:"푸른 꼭대기",clip:"polygon(8% 0%,92% 0%,90% 34%,69% 29%,50% 36%,31% 29%,10% 34%)"},{name:"돌다리",clip:"polygon(28% 61%,72% 61%,82% 93%,18% 93%)"},{name:"왼쪽 꽃정원",clip:"polygon(0% 62%,38% 58%,42% 100%,0% 100%)"},{name:"오른쪽 꽃정원",clip:"polygon(62% 58%,100% 62%,100% 100%,58% 100%)"},
  {name:"왼쪽 숲",clip:"polygon(0% 20%,20% 15%,27% 70%,0% 76%)"},{name:"오른쪽 숲",clip:"polygon(80% 15%,100% 20%,100% 76%,73% 70%)"},{name:"하늘과 깃발",clip:"polygon(0% 0%,100% 0%,100% 23%,0% 23%)"},{name:"성 앞 물가",clip:"polygon(15% 82%,85% 82%,100% 100%,0% 100%)"}],
 ranch:[
  {name:"빨간 창고",clip:"polygon(13% 20%,55% 20%,58% 58%,10% 60%)"},{name:"목장 집",clip:"polygon(48% 27%,78% 27%,81% 59%,46% 59%)"},{name:"말",clip:"polygon(0% 48%,35% 42%,39% 78%,0% 82%)"},{name:"소",clip:"polygon(69% 42%,100% 39%,100% 69%,67% 70%)"},
  {name:"양",clip:"polygon(47% 58%,81% 55%,85% 83%,43% 84%)"},{name:"풍차와 사일로",clip:"polygon(70% 5%,100% 5%,100% 47%,68% 47%)"},{name:"왼쪽 울타리",clip:"polygon(0% 65%,48% 62%,50% 91%,0% 96%)"},{name:"오른쪽 울타리",clip:"polygon(62% 64%,100% 60%,100% 91%,58% 91%)"},
  {name:"왼쪽 꽃밭",clip:"polygon(0% 76%,42% 70%,47% 100%,0% 100%)"},{name:"오른쪽 꽃밭",clip:"polygon(58% 70%,100% 73%,100% 100%,53% 100%)"},{name:"하늘과 구름",clip:"polygon(0% 0%,100% 0%,100% 26%,0% 26%)"},{name:"목장 오솔길",clip:"polygon(35% 63%,63% 62%,75% 100%,23% 100%)"}],
 mansion:[
  {name:"현관",clip:"polygon(39% 43%,61% 43%,63% 70%,37% 70%)"},{name:"대저택 본관",clip:"polygon(19% 22%,81% 22%,83% 57%,17% 57%)"},{name:"왼쪽 별관",clip:"polygon(2% 32%,33% 30%,35% 64%,0% 67%)"},{name:"오른쪽 별관",clip:"polygon(67% 30%,98% 32%,100% 67%,65% 64%)"},
  {name:"지붕과 창문",clip:"polygon(8% 13%,92% 13%,91% 42%,69% 34%,50% 42%,31% 34%,9% 42%)"},{name:"수영장",clip:"polygon(57% 56%,100% 53%,100% 86%,52% 88%)"},{name:"중앙 분수",clip:"polygon(24% 66%,62% 64%,65% 95%,18% 96%)"},{name:"왼쪽 정원",clip:"polygon(0% 57%,35% 53%,39% 100%,0% 100%)"},
  {name:"오른쪽 정원",clip:"polygon(65% 51%,100% 50%,100% 100%,61% 100%)"},{name:"양쪽 나무",clip:"polygon(0% 10%,18% 8%,25% 64%,0% 70%,75% 8%,100% 10%,100% 70%,77% 64%)"},{name:"하늘과 구름",clip:"polygon(0% 0%,100% 0%,100% 22%,0% 22%)"},{name:"정원 산책로",clip:"polygon(29% 82%,72% 80%,88% 100%,10% 100%)"}],
 apartment:[
  {name:"거실",clip:"polygon(37% 43%,72% 37%,76% 79%,34% 83%)"},{name:"침실",clip:"polygon(8% 27%,39% 27%,41% 70%,6% 72%)"},{name:"주방",clip:"polygon(63% 19%,100% 18%,100% 65%,70% 65%)"},{name:"다이닝 공간",clip:"polygon(40% 26%,69% 25%,70% 61%,39% 63%)"},
  {name:"책장과 액자",clip:"polygon(6% 7%,44% 7%,44% 39%,6% 39%)"},{name:"베란다",clip:"polygon(0% 65%,100% 61%,100% 100%,0% 100%)"},{name:"왼쪽 화분",clip:"polygon(0% 45%,28% 42%,31% 91%,0% 94%)"},{name:"오른쪽 화분",clip:"polygon(76% 42%,100% 39%,100% 92%,73% 92%)"},
  {name:"소파와 탁자",clip:"polygon(26% 56%,78% 51%,82% 92%,21% 96%)"},{name:"조명과 천장",clip:"polygon(0% 0%,100% 0%,100% 27%,0% 27%)"},{name:"아파트 외경",clip:"polygon(0% 8%,12% 8%,12% 68%,0% 73%,88% 5%,100% 5%,100% 48%,88% 48%)"},{name:"바닥과 작은 장식",clip:"polygon(0% 78%,100% 72%,100% 100%,0% 100%)"}],
 cottage:[
  {name:"현관문",clip:"polygon(39% 42%,59% 42%,62% 70%,36% 70%)"},{name:"전원주택 본체",clip:"polygon(20% 25%,80% 25%,82% 61%,18% 61%)"},{name:"왼쪽 지붕",clip:"polygon(8% 15%,48% 13%,51% 38%,12% 38%)"},{name:"오른쪽 지붕",clip:"polygon(49% 11%,91% 14%,88% 40%,49% 38%)"},
  {name:"창문과 꽃화분",clip:"polygon(18% 31%,84% 31%,84% 59%,17% 59%)"},{name:"오른쪽 과일나무",clip:"polygon(78% 10%,100% 8%,100% 65%,75% 67%)"},{name:"왼쪽 꽃밭",clip:"polygon(0% 50%,39% 48%,43% 100%,0% 100%)"},{name:"오른쪽 꽃밭",clip:"polygon(61% 49%,100% 50%,100% 100%,57% 100%)"},
  {name:"정원 우물",clip:"polygon(61% 57%,87% 56%,90% 87%,58% 88%)"},{name:"왼쪽 나무와 연못",clip:"polygon(0% 6%,24% 8%,30% 82%,0% 86%)"},{name:"하늘과 새",clip:"polygon(0% 0%,100% 0%,100% 23%,0% 23%)"},{name:"돌 산책로",clip:"polygon(34% 59%,66% 58%,82% 100%,19% 100%)"}],
 cafe:[
  {name:"카페 출입문",clip:"polygon(43% 38%,61% 38%,63% 78%,40% 78%)"},{name:"카페 본체",clip:"polygon(21% 23%,84% 22%,87% 72%,18% 72%)"},{name:"빨간 지붕",clip:"polygon(15% 8%,85% 8%,91% 34%,10% 34%)"},{name:"왼쪽 창문",clip:"polygon(18% 33%,45% 31%,46% 70%,16% 71%)"},
  {name:"오른쪽 제빵 진열장",clip:"polygon(58% 31%,91% 29%,94% 70%,57% 70%)"},{name:"야외 파라솔",clip:"polygon(0% 23%,27% 20%,29% 70%,0% 72%)"},{name:"왼쪽 꽃화분",clip:"polygon(0% 57%,39% 54%,42% 100%,0% 100%)"},{name:"오른쪽 꽃화분",clip:"polygon(64% 54%,100% 54%,100% 100%,60% 100%)"},
  {name:"야외 테이블",clip:"polygon(4% 59%,42% 55%,47% 94%,0% 96%)"},{name:"의자와 입구 계단",clip:"polygon(38% 65%,90% 61%,96% 100%,30% 100%)"},{name:"하늘과 나뭇잎",clip:"polygon(0% 0%,100% 0%,100% 25%,0% 25%)"},{name:"카페 앞 꽃길",clip:"polygon(0% 82%,100% 78%,100% 100%,0% 100%)"}],
 money:[
  {name:"돼지저금통 얼굴",clip:"polygon(35% 23%,68% 22%,71% 77%,32% 78%)"},{name:"돼지저금통 몸",clip:"polygon(27% 30%,76% 28%,79% 86%,24% 86%)"},{name:"왕관",clip:"polygon(34% 0%,70% 0%,68% 32%,35% 32%)"},{name:"왼쪽 금화 단지",clip:"polygon(0% 23%,32% 22%,36% 82%,0% 84%)"},
  {name:"오른쪽 금화 단지",clip:"polygon(69% 22%,100% 22%,100% 84%,66% 82%)"},{name:"왼쪽 금화 더미",clip:"polygon(0% 60%,41% 56%,44% 100%,0% 100%)"},{name:"오른쪽 금화 더미",clip:"polygon(61% 55%,100% 58%,100% 100%,58% 100%)"},{name:"꿈 통장",clip:"polygon(55% 57%,84% 55%,87% 95%,52% 95%)"},
  {name:"왼쪽 꽃",clip:"polygon(0% 15%,21% 12%,27% 66%,0% 70%)"},{name:"오른쪽 꽃",clip:"polygon(80% 12%,100% 15%,100% 70%,74% 66%)"},{name:"하늘과 햇살",clip:"polygon(0% 0%,100% 0%,100% 24%,0% 24%)"},{name:"바닥의 동전",clip:"polygon(10% 78%,91% 76%,100% 100%,0% 100%)"}]
};
const OBJECT_PART_NAMES:Record<MissionId,string[]>={
 palace:["왕궁 지붕과 첨탑","왕궁 본관","왼쪽 탑","오른쪽 탑","문과 창문","정원 분수","양쪽 꽃밭","나무줄기와 가지","왼쪽 나뭇잎","오른쪽 나뭇잎","하늘과 구름","왕궁 산책로"],
 castle:["성의 지붕과 첨탑","중앙 본성","왼쪽 성탑","오른쪽 성탑","성문과 창문","돌다리","왼쪽 꽃정원","오른쪽 꽃정원","왼쪽 숲","오른쪽 숲","하늘과 깃발","성 앞 물가"],
 ranch:["창고와 집의 지붕","목장 건물","말","소","양","풍차와 사일로","왼쪽 울타리","오른쪽 울타리","왼쪽 꽃밭","오른쪽 꽃밭","하늘과 구름","목장 오솔길"],
 mansion:["대저택 지붕","대저택 본관","왼쪽 별관","오른쪽 별관","현관과 창문","중앙 분수","왼쪽 정원","오른쪽 정원","왼쪽 나무","오른쪽 나무","하늘과 구름","수영장"],
 apartment:["왼쪽 생활공간","침실","주방","다이닝 공간","책장과 액자","베란다와 바닥","왼쪽 화분","오른쪽 화분","소파와 탁자","조명과 천장","아파트 외경","바닥과 작은 장식"],
 cottage:["전원주택 지붕","전원주택 본체","현관문","창문과 꽃화분","왼쪽 꽃밭","오른쪽 꽃밭","오른쪽 과일나무와 잎","왼쪽 나무와 잎","정원 연못","정원 우물","하늘과 새","돌 산책로"],
 cafe:["카페 지붕","카페 본체","카페 출입문","제빵 진열창","차양","야외 파라솔","왼쪽 꽃화분","오른쪽 꽃화분","야외 테이블과 의자","큰 나무와 잎","하늘","카페 앞 꽃길"],
 money:["돼지저금통 몸","돼지저금통 얼굴","왕관","왼쪽 금화 단지","오른쪽 금화 단지","왼쪽 금화 더미","오른쪽 금화 더미","꿈 통장","왼쪽 꽃과 나무","오른쪽 꽃과 나무","하늘과 햇살","바닥의 동전"]
};
const STUDY=["매일 수업 시작 5분 전에 다음 수업을 준비하기","매일 수업 전 5분 동안 나의 학습계획 실천하기","매일 수학 문제 5개 풀기","매일 영어 단어 20개 이상 익히기","매일 책을 20분 이상 읽기","그날 배운 내용을 10분 동안 복습하기","학교에서 받은 과제를 정해진 날까지 완료하기","수업 시간에 한 번 이상 질문하거나 발표하기"];
const LIFE=["매일 30분 정도 운동하기","잠자기 전에 다음 날 가방 정리하기","사용한 물건을 제자리에 정리하기","친구에게 따뜻한 말 한 번 건네기","가족에게 먼저 인사하기","정해진 시간에 잠자리에 들기","비속어를 사용하지 않고 바른말 쓰기"];
const KEY="promise-challenge-v1",today=()=>new Date().toISOString().slice(0,10);
const fmt=(d:string)=>new Date(d+"T12:00:00").toLocaleDateString("ko-KR",{month:"long",day:"numeric",weekday:"short"});
const taskList=(s:Student,type:"study"|"life")=>type==="study"?(s.studyTasks?.length?s.studyTasks:[s.studyTask||""]):(s.lifeTasks?.length?s.lifeTasks:[s.lifeTask||""]);
const hasCheck=(keys:string[],type:"study"|"life",i:number,total:number)=>keys.includes(`${type}${i}`)||(total===1&&keys.includes(type));
const categoryDone=(s:Student,keys:string[],type:"study"|"life")=>taskList(s,type).every((_,i,a)=>hasCheck(keys,type,i,a.length));
const days=(s:Student)=>Object.values(s.checks).filter(v=>categoryDone(s,v,"study")&&categoryDone(s,v,"life")).length;
const growth=(s:Student)=>Object.values(s.checks).reduce((sum,v)=>sum+(categoryDone(s,v,"study")&&categoryDone(s,v,"life")?1:0)+(v.includes("extra1")?.5:0)+(v.includes("extra2")?.5:0),0);
function streak(s:Student){let n=0,d=new Date();for(let i=0;i<100;i++){const v=s.checks[d.toISOString().slice(0,10)]||[];if(categoryDone(s,v,"study")&&categoryDone(s,v,"life"))n++;else if(i>0)break;d.setDate(d.getDate()-1)}return n}
function automaticUnits(total:number){return Array.from({length:12},(_,i)=>Math.max(0,Math.min(5,total-i*5)))}
function colorUnits(s:Student,total=days(s)){return s.colorAllocations?.length===12?s.colorAllocations.map(v=>Math.max(0,Math.min(5,Number(v)||0))):automaticUnits(total)}
function changeColorByDay(s:Student,totalBefore:number,delta:1|-1){
 if(!s.colorAllocations&&(s.colorMode||"auto")==="auto")return s;
 const units=[...colorUnits(s,totalBefore)];let bank=Math.max(0,s.unspentColorDays||0);
 if(delta===1){
  const chosen=(s.colorMode||"auto")==="manual"?s.selectedColorPart:units.findIndex(v=>v<5);
  if(chosen!==undefined&&chosen>=0&&chosen<12&&units[chosen]<5)units[chosen]++;else bank++;
 }else if(bank>0)bank--;else{let chosen=(s.colorMode||"auto")==="manual"?s.selectedColorPart:undefined;if(chosen===undefined||units[chosen]<=0)chosen=units.findLastIndex(v=>v>0);if(chosen>=0)units[chosen]--}
 return {...s,colorAllocations:units,unspentColorDays:bank};
}

export default function Home(){
 const [students,setStudents]=useState<Student[]>([]),[activeId,setActiveId]=useState<string|null>(null),[tab,setTab]=useState("today"),[setup,setSetup]=useState(false),[step,setStep]=useState(0),[reward,setReward]=useState(false),[adminMode,setAdminMode]=useState(false),[zoom,setZoom]=useState(false);
 const [form,setForm]=useState({grade:"1",classNo:"1",number:"1",name:"",studyTasks:[] as string[],lifeTasks:[] as string[],studyCustom:"",lifeCustom:"",extra1:"",extra2:"",mission:"palace" as MissionId});const fileRef=useRef<HTMLInputElement>(null);
 const [finder,setFinder]=useState({grade:"",classNo:"",number:"",name:""});
 useEffect(()=>{try{const r=localStorage.getItem(KEY);if(r)setStudents(JSON.parse(r))}catch{}},[]);useEffect(()=>{if(students.length)localStorage.setItem(KEY,JSON.stringify(students))},[students]);
 const active=students.find(s=>s.id===activeId)||null,cur=active?.checks[today()]||[],total=active?days(active):0,mission=MISSIONS.find(m=>m.id===active?.mission)||MISSIONS[0],levels=active?colorUnits(active,total):automaticUnits(0);
 const finderReady=Boolean(finder.grade&&finder.classNo&&(finder.number.trim()||finder.name.trim()));
 const foundStudents=finderReady?students.filter(s=>s.grade===finder.grade&&s.classNo===finder.classNo&&(!finder.number.trim()||s.number===finder.number.trim())&&(!finder.name.trim()||s.name.includes(finder.name.trim()))):[];
 function create(){const study=[...form.studyTasks,form.studyCustom.trim()].filter(Boolean).slice(0,3),life=[...form.lifeTasks,form.lifeCustom.trim()].filter(Boolean).slice(0,3);if(!form.name.trim()||!study.length||!life.length)return;const s:Student={grade:form.grade,classNo:form.classNo,number:form.number,name:form.name.trim(),studyTasks:study,lifeTasks:life,extra1:form.extra1,extra2:form.extra2,mission:form.mission,id:`${form.grade}-${form.classNo}-${form.number}-${Date.now()}`,startDate:today(),checks:{}};setStudents(v=>[...v,s]);setActiveId(s.id);setSetup(false);setStep(0);setTab("today")}
 function toggle(k:string){if(!active)return;const before=categoryDone(active,cur,"study")&&categoryDone(active,cur,"life"),next=cur.includes(k)?cur.filter(x=>x!==k):[...cur,k],after=categoryDone(active,next,"study")&&categoryDone(active,next,"life");setStudents(v=>v.map(s=>{if(s.id!==active.id)return s;let changed={...s,checks:{...s.checks,[today()]:next}};if(!before&&after)changed=changeColorByDay(changed,total,1);if(before&&!after)changed=changeColorByDay(changed,total,-1);return changed}));if(!before&&after&&(total+1)%5===0)setTimeout(()=>setReward(true),250)}
 function setColorMode(mode:ColorMode){if(!active)return;setStudents(v=>v.map(s=>{if(s.id!==active.id)return s;const units=[...colorUnits(s)],bank=Math.max(0,s.unspentColorDays||0);if(mode==="auto"&&bank){let left=bank;while(left>0){const i=units.findIndex(n=>n<5);if(i<0)break;units[i]++;left--}return {...s,colorMode:mode,colorAllocations:units,unspentColorDays:left}}return {...s,colorMode:mode,colorAllocations:units}}))}
 function selectColorPart(index:number){if(!active)return;setStudents(v=>v.map(s=>{if(s.id!==active.id)return s;const units=[...colorUnits(s)],bank=Math.max(0,s.unspentColorDays||0),use=Math.min(bank,5-units[index]);units[index]+=use;return {...s,colorMode:"manual",selectedColorPart:index,colorAllocations:units,unspentColorDays:bank-use}}))}
 function backup(){const b=new Blob([JSON.stringify({app:"나의 약속 챌린지",version:1,exportedAt:new Date().toISOString(),students},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=`나의약속챌린지_백업_${today()}.json`;a.click();URL.revokeObjectURL(a.href)}
 function removeStudent(id:string){const target=students.find(s=>s.id===id);if(!target||!confirm(`${target.grade}학년 ${target.classNo}반 ${target.number}번 ${target.name} 학생의 자료를 삭제할까요?`))return;backup();const next=students.filter(s=>s.id!==id);setStudents(next);if(!next.length)localStorage.removeItem(KEY)}
 function removeAll(){if(!students.length)return;if(!confirm(`전체 ${students.length}명의 자료를 삭제할까요? 삭제 전에 백업파일이 내려받아집니다.`))return;backup();setStudents([]);localStorage.removeItem(KEY)}
 function restore(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(String(r.result));if(!Array.isArray(d.students))throw 0;if(confirm(`${d.students.length}명의 기록을 가져올까요?`)){setStudents(d.students);setActiveId(null);alert("자료를 정상적으로 가져왔습니다.")}}catch{alert("올바른 백업파일이 아닙니다.")}};r.readAsText(f);e.target.value=""}
 if(setup)return <Setup form={form} setForm={setForm} step={step} setStep={setStep} done={create} cancel={()=>{setSetup(false);setStep(0)}}/>;
 if(adminMode)return <AdminScreen students={students} close={()=>setAdminMode(false)} backup={backup} restore={restore} removeStudent={removeStudent} removeAll={removeAll} fileRef={fileRef}/>;
 if(!active)return <main className="landing"><button className="admin-entry" onClick={()=>setAdminMode(true)}>⚙ 관리자</button><div className="orb a"/><div className="orb b"/><section className="welcome"><div className="brand">✓</div><p className="eyebrow">12주 동안 나와 지키는 약속</p><h1>나의 약속 챌린지</h1><p className="lead">매일 작은 실천을 기록하고<br/>나만의 멋진 미션을 완성해요.</p>{students.length>0&&<><div className="student-search"><p>내 기록 빠르게 찾기</p><div className="student-finder"><label>학년<select aria-label="기록 찾기 학년" value={finder.grade} onChange={e=>setFinder({...finder,grade:e.target.value})}><option value="">선택</option>{[1,2,3].map(n=><option key={n} value={String(n)}>{n}학년</option>)}</select></label><label>반<select aria-label="기록 찾기 반" value={finder.classNo} onChange={e=>setFinder({...finder,classNo:e.target.value})}><option value="">선택</option>{[1,2,3,4,5,6].map(n=><option key={n} value={String(n)}>{n}반</option>)}</select></label><label>번호<input aria-label="기록 찾기 번호" inputMode="numeric" placeholder="예: 12" value={finder.number} onChange={e=>setFinder({...finder,number:e.target.value.replace(/\D/g,"")})}/></label><label>이름<input aria-label="기록 찾기 이름" placeholder="이름" value={finder.name} onChange={e=>setFinder({...finder,name:e.target.value})}/></label></div>{!finderReady&&<div className="finder-guide">학년·반을 선택하고 번호 또는 이름을 입력하세요.</div>}{finderReady&&foundStudents.length===0&&<div className="finder-empty">일치하는 기록이 없습니다.</div>}{finderReady&&foundStudents.length>0&&<div className="student-list search-results">{foundStudents.map(s=><button key={`found-${s.id}`} onClick={()=>setActiveId(s.id)}><span>{MISSIONS.find(m=>m.id===s.mission)?.icon}</span><span><b>{s.grade}학년 {s.classNo}반 {s.number}번 {s.name}</b><small>{MISSIONS.find(m=>m.id===s.mission)?.label} · {days(s)}일 달성</small></span><i>›</i></button>)}</div>}</div><div className="student-list"><p>등록된 학생</p>{students.map(s=><button key={s.id} onClick={()=>setActiveId(s.id)}><span>{MISSIONS.find(m=>m.id===s.mission)?.icon}</span><span><b>{s.grade}학년 {s.classNo}반 {s.number}번 {s.name}</b><small>{MISSIONS.find(m=>m.id===s.mission)?.label} · {days(s)}일 달성</small></span><i>›</i></button>)}</div></>}<button className="primary jumbo" onClick={()=>setSetup(true)}>＋ 새 도전 시작하기</button><small className="privacy">이 기록은 현재 기기에만 저장됩니다 · 학교 공용 컴퓨터를 공식 기록기기로 사용하세요</small></section></main>;
 return <main className="shell"><header><button className="logo" onClick={()=>setActiveId(null)}><span>✓</span> 나의 약속 챌린지</button><div className="student-chip"><b>{active.grade}학년 {active.classNo}반 {active.number}번</b><span>{active.name}</span><button onClick={()=>setActiveId(null)}>나가기</button></div></header><nav>{[["today","✓","오늘의 실천"],["challenge","◷","나의 도전"],["mission","★","나의 미션"],["history","▥","성장기록"],["intro","▦","미션 그림 소개"]].map(([k,i,l])=><button key={k} className={tab===k?"on":""} onClick={()=>setTab(k)}><i>{i}</i>{l}</button>)}</nav><section className="content">
 {tab==="today"&&<><Heading over={fmt(today())} title="오늘도 약속을 실천해 볼까요?" side={<div className="streak">🔥 <b>{streak(active)}일</b><span>연속 실천</span></div>}/><div className="today-grid"><div className="tasks">{taskList(active,"study").map((text,i,a)=><Task key={`study${i}`} kind="study" title={`학습 실천과제 ${a.length>1?i+1:""}`} text={text} checked={hasCheck(cur,"study",i,a.length)} required onClick={()=>toggle(`study${i}`)}/>)}{taskList(active,"life").map((text,i,a)=><Task key={`life${i}`} kind="life" title={`생활 실천과제 ${a.length>1?i+1:""}`} text={text} checked={hasCheck(cur,"life",i,a.length)} required onClick={()=>toggle(`life${i}`)}/>)}{(active.extra1||active.extra2)&&<div className="bonus-guide">🚀 기타 실천과제는 보너스로 기록돼요. 그림은 필수 약속을 모두 지킨 날마다 한 부분씩 색칠됩니다.</div>}{active.extra1&&<Task kind="extra" title="기타 실천과제 1 · 보너스 +0.5" text={active.extra1} checked={cur.includes("extra1")} onClick={()=>toggle("extra1")}/>} {active.extra2&&<Task kind="extra" title="기타 실천과제 2 · 보너스 +0.5" text={active.extra2} checked={cur.includes("extra2")} onClick={()=>toggle("extra2")}/>}<ColorControls s={active} total={total} onMode={setColorMode} onSelect={selectColorPart}/>{categoryDone(active,cur,"study")&&categoryDone(active,cur,"life")&&<div className="complete">✨ 오늘의 필수 약속을 모두 지켰어요!<strong>{colorMessage(active,total)}</strong></div>}</div><Preview s={active} total={total} levels={levels} onOpen={()=>setZoom(true)}/></div></>}
 {tab==="challenge"&&<><Heading over="나의 12주 도전" title={`${active.name} 학생의 꾸준한 발걸음`}/><div className="stats"><Stat n={`${total}일`} l="필수과제 달성"/><Stat n={`${streak(active)}일`} l="연속 실천"/><Stat n={`${Math.min(100,Math.round(growth(active)/60*100))}%`} l="미션 완성도"/><Stat n={`${growth(active)-total}점`} l="기타과제 보너스"/></div><div className="challenge"><div className="ring" style={{"--p":`${Math.min(100,growth(active)/60*100)*3.6}deg`} as React.CSSProperties}><b>{Math.min(100,Math.round(growth(active)/60*100))}%</b><span>완성</span></div><div><p className="eyebrow">선택한 미션</p><h3>{active.name}의 {mission.label}</h3><p>필수 약속은 하루 1점, 기타 실천과제는 각각 0.5점씩 더 성장합니다.</p><div className="progress"><i style={{width:`${Math.min(100,growth(active)/60*100)}%`}}/></div><small>12주 목표 60점 중 {growth(active)}점 성장</small></div></div></>}
 {tab==="mission"&&<><Heading over="나의 미션" title={`${active.name}의 ${mission.label}`}/><Stage s={active} total={total} levels={levels} onOpen={()=>setZoom(true)}/></>}
 {tab==="history"&&<History s={active}/>} 
 {tab==="intro"&&<MissionIntro/>}
 </section>{reward&&<div className="modal"><div className="reward"><div>🎉</div><h2>5일 실천에 성공했어요!</h2><p>꾸준히 약속을 지킨 여러분이 자랑스러워요.</p><strong>상품을 선생님께 받아 가세요!</strong><button className="primary" onClick={()=>setReward(false)}>확인했어요</button></div></div>}{zoom&&<div className="image-modal" onClick={()=>setZoom(false)}><button aria-label="전체화면 닫기">×</button><div className="full-art object-color-art" onClick={e=>e.stopPropagation()}><ObjectColorArt mission={active.mission} total={total} levels={levels}/><div className="plaque">{active.name}의 {mission.label}</div><div className="full-progress">실천 {total}일 · {Math.round(levels.reduce((a,b)=>a+b,0)/60*100)}% 채색</div></div></div>}</main>
}

function AdminScreen({students,close,backup,restore,removeStudent,removeAll,fileRef}:{students:Student[];close:()=>void;backup:()=>void;restore:(e:React.ChangeEvent<HTMLInputElement>)=>void;removeStudent:(id:string)=>void;removeAll:()=>void;fileRef:React.RefObject<HTMLInputElement|null>}){
 const [unlocked,setUnlocked]=useState(false),[pin,setPin]=useState(""),[error,setError]=useState(false);
 function enter(){if(pin==="6673"){setUnlocked(true);setError(false)}else{setError(true);setPin("")}}
 if(!unlocked)return <main className="admin-page"><section className="admin-login"><button className="back" onClick={close}>← 첫 화면</button><div className="admin-lock">🔒</div><p className="eyebrow">교사 전용</p><h1>관리자 화면</h1><p>관리 비밀번호 4자리를 입력하세요.</p><input type="password" inputMode="numeric" maxLength={4} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))} onKeyDown={e=>{if(e.key==="Enter")enter()}} autoFocus aria-label="관리자 비밀번호"/>{error&&<small className="pin-error">비밀번호가 맞지 않습니다.</small>}<button className="primary" disabled={pin.length!==4} onClick={enter}>관리자 화면 열기</button></section></main>;
 return <main className="admin-page"><section className="admin-panel"><div className="admin-head"><div><p className="eyebrow">교사 전용 관리</p><h1>학생 기록 관리</h1><span>등록 학생 {students.length}명</span></div><button onClick={close}>× 닫기</button></div><div className="admin-grid"><button onClick={backup}><span>↓</span><b>전체 자료 백업하기</b><small>{students.length}명의 기록을 파일로 저장합니다.</small></button><button onClick={()=>fileRef.current?.click()}><span>↑</span><b>백업자료 가져오기</b><small>저장해 둔 기록을 이 컴퓨터에 복원합니다.</small></button><input ref={fileRef} type="file" accept=".json" hidden onChange={restore}/></div><div className="warning">삭제하면 먼저 전체 백업파일이 자동으로 내려받아집니다.</div><div className="manage-list"><h2>학생별 자료 삭제</h2>{students.length?students.map(s=><div key={s.id}><span className="student-avatar">{MISSIONS.find(m=>m.id===s.mission)?.icon}</span><span><b>{s.grade}학년 {s.classNo}반 {s.number}번 {s.name}</b><small>{MISSIONS.find(m=>m.id===s.mission)?.label} · {days(s)}일 달성 · 성장 {growth(s)}점</small></span><button onClick={()=>removeStudent(s.id)}>삭제</button></div>):<p className="empty">등록된 학생 자료가 없습니다.</p>}</div>{students.length>0&&<button className="delete-all" onClick={removeAll}>전체 학생 자료 삭제</button>}</section></main>
}

function Setup({form,setForm,step,setStep,done,cancel}:{form:any;setForm:any;step:number;setStep:any;done:()=>void;cancel:()=>void}){const studyCount=form.studyTasks.length+(form.studyCustom.trim()?1:0),lifeCount=form.lifeTasks.length+(form.lifeCustom.trim()?1:0),ok=step===0?form.name.trim():step===1?studyCount>0:step===2?lifeCount>0:true;return <main className="setup"><section className="setup-card"><button className="back" onClick={step?()=>setStep(step-1):cancel}>← 이전</button><div className="steps">{[0,1,2,3,4].map(i=><i key={i} className={i<=step?"on":""}/>)}</div>{step===0&&<><p className="eyebrow">1 / 5 · 학생정보</p><h1>나의 도전을 시작해요</h1><p className="sub">기록을 찾을 때 사용할 정보를 입력하세요.</p><div className="fields">{[["학년","grade",3],["반","classNo",6]].map(([l,k,n]:any)=><label key={k}>{l}<select value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}>{Array.from({length:n},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label>)}<label>번호<input type="number" min="1" max="40" value={form.number} onChange={e=>setForm({...form,number:e.target.value})}/></label><label>이름<input placeholder="이름" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label></div></>}{step===1&&<TaskSetup n="2" type="학습" title="학습 실천과제를 정해요" guide="예시를 체크하고 직접 입력도 함께 할 수 있어요. 최대 3개를 선택하세요." examples={STUDY} selected={form.studyTasks} custom={form.studyCustom} changeSelected={(v:string[])=>setForm({...form,studyTasks:v})} changeCustom={(v:string)=>setForm({...form,studyCustom:v})}/>} {step===2&&<TaskSetup n="3" type="생활" title="생활 실천과제를 정해요" guide="예시를 체크하고 직접 입력도 함께 할 수 있어요. 최대 3개를 선택하세요." examples={LIFE} selected={form.lifeTasks} custom={form.lifeCustom} changeSelected={(v:string[])=>setForm({...form,lifeTasks:v})} changeCustom={(v:string)=>setForm({...form,lifeCustom:v})}/>} {step===3&&<><p className="eyebrow">4 / 5 · 선택사항</p><h1>더 도전해 볼까요?</h1><p className="sub">기타과제는 하나를 완료할 때마다 미션 성장점수 0.5점을 더 받아요.</p><label className="wide">기타 실천과제 1<input placeholder="예: 가족에게 먼저 인사하기" value={form.extra1} onChange={e=>setForm({...form,extra1:e.target.value})}/></label><label className="wide">기타 실천과제 2<input placeholder="예: 사용한 물건 제자리에 놓기" value={form.extra2} onChange={e=>setForm({...form,extra2:e.target.value})}/></label></>} {step===4&&<><p className="eyebrow">5 / 5 · 미션 선택</p><h1>3개월 동안 무엇을 완성할까요?</h1><p className="sub">마음에 드는 미션 하나를 선택하세요.</p><div className="mission-select">{MISSIONS.map(m=><button key={m.id} onClick={()=>setForm({...form,mission:m.id})} className={form.mission===m.id?"chosen":""} style={{"--mission":m.color} as React.CSSProperties}><span>{m.icon}</span><b>{m.label}</b><small>{m.desc}</small><i>✓</i></button>)}</div></>}<div className="setup-actions"><button className="primary" disabled={!ok} onClick={step<4?()=>setStep(step+1):done}>{step<4?"다음":"이 약속으로 도전 시작하기"}</button></div></section></main>}
function TaskSetup({n,type,title,guide,examples,selected,custom,changeSelected,changeCustom}:{n:string;type:string;title:string;guide:string;examples:string[];selected:string[];custom:string;changeSelected:(v:string[])=>void;changeCustom:(v:string)=>void}){const count=selected.length+(custom.trim()?1:0);function pick(x:string){if(selected.includes(x))changeSelected(selected.filter(v=>v!==x));else if(count<3)changeSelected([...selected,x])}return <><p className="eyebrow">{n} / 5 · {type} 실천과제 <em>1~3개</em></p><h1>{title}</h1><p className="sub">{guide} <b className="count">현재 {count}/3개</b></p><div className="examples">{examples.map(x=><button key={x} className={selected.includes(x)?"selected":""} disabled={!selected.includes(x)&&count>=3} onClick={()=>pick(x)}><i>{selected.includes(x)?"✓":"○"}</i>{x}</button>)}</div><label className="wide">직접 입력하기<textarea placeholder="선택한 예시와 함께 나만의 과제도 추가할 수 있어요." value={custom} disabled={!custom&&selected.length>=3} onChange={e=>changeCustom(e.target.value)}/></label></>}
function Heading({over,title,side}:{over:string;title:string;side?:React.ReactNode}){return <div className="heading"><div><p>{over}</p><h2>{title}</h2></div>{side}</div>}
function Task({kind,title,text,checked,required,onClick}:{kind:string;title:string;text:string;checked:boolean;required?:boolean;onClick:()=>void}){return <button className={`task ${kind} ${checked?"done":""}`} onClick={onClick}><span>{kind==="study"?"📘":kind==="life"?"🌿":"⭐"}</span><span><small>{title} {required&&<em>필수</em>}</small><b>{text}</b></span><i>{checked?"✓":""}</i></button>}
const colorPercent=(total:number)=>Math.min(100,total/60*100);
function partState(total:number,index:number){const safe=Math.max(0,Math.min(60,total)),completed=Math.floor(safe/5),remainder=safe%5;if(index<completed)return 100;if(index===completed&&remainder>0)return remainder*20;return 0}
function ColorControls({s,total,onMode,onSelect}:{s:Student;total:number;onMode:(mode:ColorMode)=>void;onSelect:(index:number)=>void}){
 const mode=s.colorMode||"auto",units=colorUnits(s,total),parts=OBJECT_PART_NAMES[s.mission],bank=Math.max(0,s.unspentColorDays||0);
 return <section className={`color-controls ${mode}`}><div className="color-control-head"><span>🎨</span><div><b>미션 채색 방법</b><small>실천한 하루마다 사물 한 곳에 색이 20%씩 채워져요.</small></div></div><div className="color-mode-buttons"><button className={mode==="auto"?"selected":""} onClick={()=>onMode("auto")}><b>자동 채색</b><small>정해진 순서대로</small></button><button className={mode==="manual"?"selected":""} onClick={()=>onMode("manual")}><b>수동 채색</b><small>내가 사물을 선택</small></button></div>{mode==="manual"&&<><div className="manual-guide">{bank>0?<b>사용 가능한 채색 {bank}회 · 사물을 선택하세요.</b>:<span>색칠할 사물을 선택하면 다음 실천부터 그곳에 색이 채워집니다.</span>}</div><div className="color-part-grid">{parts.map((name,i)=><button key={name} className={`${s.selectedColorPart===i?"chosen":""} ${units[i]>=5?"finished":""}`} onClick={()=>onSelect(i)}><span>{units[i]>=5?"✓":`${units[i]}/5`}</span><b>{name}</b><small>{units[i]>=5?"완성":s.selectedColorPart===i?"선택됨":"선택하기"}</small></button>)}</div></>}{mode==="auto"&&<div className="auto-guide">현재 기본 순서에서 아직 완성되지 않은 사물을 자동으로 채색합니다.</div>}</section>;
}
function colorMessage(s:Student,total:number){const parts=OBJECT_PART_NAMES[s.mission],units=colorUnits(s,total),painted=units.reduce((a,b)=>a+b,0);if(painted>=60)return `모든 건물과 꽃이 완전히 채색되었어요!`;if((s.colorMode||"auto")==="manual"){const i=s.selectedColorPart;if(i===undefined)return s.unspentColorDays?"색칠할 사물을 선택해 주세요.":"다음에 색칠할 사물을 선택할 수 있어요.";return `${parts[i]} 채색 ${units[i]}/5${units[i]>=5?" · 완성!":""}`}if(total<=0)return `첫 번째 ${parts[0]}에 색을 채워 볼까요?`;const index=s.colorAllocations?Math.max(0,units.findIndex(v=>v<5)):Math.floor((total-1)/5),step=index>=0?units[index]:5;return `자동 채색: ${parts[index<0?11:index]} (${step}/5)`}
function ObjectColorArt({mission,total,levels}:{mission:MissionId;total:number;levels?:number[]}){
 const canvasRef=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{
  let stopped=false,loaded=0;
  const source=new Image(),mask=new Image();
  function paint(){
   if(stopped||++loaded<2)return;
   const canvas=canvasRef.current;
   if(!canvas)return;
   const width=Math.min(760,source.naturalWidth),height=Math.round(width*source.naturalHeight/source.naturalWidth);
   canvas.width=width;canvas.height=height;
   const ctx=canvas.getContext("2d",{willReadFrequently:true});
   if(!ctx)return;
   const temp=document.createElement("canvas"),tctx=temp.getContext("2d",{willReadFrequently:true});
   if(!tctx)return;
   temp.width=width;temp.height=height;
   tctx.drawImage(source,0,0,width,height);
   const color=tctx.getImageData(0,0,width,height);
   tctx.clearRect(0,0,width,height);tctx.drawImage(mask,0,0,width,height);
   const labels=tctx.getImageData(0,0,width,height).data,out=ctx.createImageData(width,height);
   for(let i=0;i<color.data.length;i+=4){
    const r=color.data[i],g=color.data[i+1],b=color.data[i+2];
    const gray=Math.max(0,Math.min(255,(((r*.299+g*.587+b*.114)-128)*1.45+128)*1.28));
    const sketch=255+(gray-255)*.68,label=Math.round(labels[i]/20)-1;
    const fill=label>=0?(levels?Math.max(0,Math.min(5,levels[label]||0))/5:total>=60?1:partState(total,label)/100):0;
    out.data[i]=sketch+(r-sketch)*fill;out.data[i+1]=sketch+(g-sketch)*fill;out.data[i+2]=sketch+(b-sketch)*fill;out.data[i+3]=255;
   }
   ctx.putImageData(out,0,0);
  }
  source.onload=paint;mask.onload=paint;
  source.src=`/missions/${mission}.webp`;mask.src=`/missions/object-masks/${mission}.png`;
  return()=>{stopped=true};
 },[mission,total,levels]);
 return <div className="object-color-layers" aria-hidden="true"><canvas ref={canvasRef} className="mission-object-canvas"/></div>;
}
function Preview({s,total,levels,onOpen}:{s:Student;total:number;levels:number[];onOpen:()=>void}){const m=MISSIONS.find(x=>x.id===s.mission)!,painted=levels.reduce((a,b)=>a+b,0);return <button aria-label={`${m.label} 그림 전체화면으로 보기`} className="preview object-color-art" onClick={onOpen}><ObjectColorArt mission={s.mission} total={total} levels={levels}/><div><p>{s.name}의</p><h3>{m.label}</h3><div className="progress light"><i style={{width:`${colorPercent(painted)}%`}}/></div><small>{Math.round(colorPercent(painted))}% 채색 · 실천 {total}일</small><em>⛶ 그림을 누르면 크게 볼 수 있어요</em></div></button>}
function Stage({s,total,levels,onOpen}:{s:Student;total:number;levels:number[];onOpen:()=>void}){const m=MISSIONS.find(x=>x.id===s.mission)!,painted=levels.reduce((a,b)=>a+b,0),level=Math.min(7,Math.floor(painted/10)+1);return <button aria-label={`${m.label} 그림 전체화면으로 보기`} className="stage object-color-art" onClick={onOpen}><ObjectColorArt mission={s.mission} total={total} levels={levels}/><div className="plaque">{s.name}의 {m.label}</div><div className="stage-info"><span>채색단계 {level} / 7</span><b>{painted<60?`${60-painted}회 더 채색하면 최종 완성!`:"60일 미션을 완성했어요!"}</b><p>{colorMessage(s,total)} · 눌러서 크게 보기</p></div></button>}
function MissionIntro(){const [selected,setSelected]=useState<MissionId>("palace"),mission=MISSIONS.find(x=>x.id===selected)!;return <><Heading over="누구나 볼 수 있는 안내" title="미션 그림이 완성되는 과정"/><p className="intro-lead">건물·나무·꽃·장식을 한 부분씩 채색하여 60일 뒤 전체 그림을 완성해요.</p><div className="intro-missions">{MISSIONS.map(m=><button key={m.id} className={selected===m.id?"selected":""} onClick={()=>setSelected(m.id)}><span>{m.icon}</span><b>{m.label}</b></button>)}</div><section className="intro-showcase"><div className="intro-final" style={{backgroundImage:`url('/missions/${mission.id}.webp')`}}><strong>{mission.label} 최종 완성 모습</strong></div><div><p className="eyebrow">60일 부분 채색</p><h3>한 부분씩 살아나는 그림</h3><p>5일 동안 하나의 건물·나무·꽃 영역에 색이 매일 더 선명해지고, 다음 5일에는 새로운 부분을 채색합니다.</p></div></section><div className="milestone-grid">{[0,10,20,30,40,50,60].map(day=><div key={day}><div className="milestone-art object-color-art"><ObjectColorArt mission={selected} total={day}/></div><b>{day===0?"시작 전":`${day}일`}</b><span>{day===0?"연필 밑그림":day===60?"전체 완성":`${Math.round(colorPercent(day))}% 부분 채색`}</span></div>)}</div></>}
function Stat({n,l}:{n:string;l:string}){return <div className="stat"><b>{n}</b><span>{l}</span></div>}
function History({s}:{s:Student}){const es=useMemo(()=>Object.entries(s.checks).sort((a,b)=>b[0].localeCompare(a[0])),[s.checks]);return <><Heading over="자동 성장기록" title="실천한 날이 차곡차곡 기록돼요"/><div className="history-summary"><b>총 {days(s)}일 달성 · 성장 {growth(s)}점</b><span>필수과제 달성일과 기타과제 보너스를 자동으로 계산합니다.</span></div><div className="history-list">{es.length?es.map(([d,k])=>{const sd=categoryDone(s,k,"study"),ld=categoryDone(s,k,"life"),bonus=(k.includes("extra1")?.5:0)+(k.includes("extra2")?.5:0);return <div key={d}><time>{fmt(d)}</time><span className={sd?"ok":""}>학습 {sd?"✓":"—"}</span><span className={ld?"ok":""}>생활 {ld?"✓":"—"}</span><b>{sd&&ld?`달성${bonus?` +${bonus}`:""}`:"진행 중"}</b></div>}):<div className="empty">아직 기록이 없습니다. 오늘의 첫 약속을 실천해 보세요!</div>}</div></>}
